version: "3.9"

services:
  api:
    build: ./
    container_name: shortlinks-api
    restart: unless-stopped
    tty: true
    stdin_open: true
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3030:3030"
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine3.15
    container_name: shortlinks-db
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    name: shortlinks_data
